In [1]:
import numpy as np
import scipy.optimize as opt
import pandas as pd
from scipy.interpolate import interp1d
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data = pd.read_csv('Lab7_Part1.csv')
data = pd.DataFrame(data).to_numpy()
p

[[ 9.99999978e-03  3.21838558e-02  0.00000000e+00]
 [ 1.99999996e-02  2.27177422e-02  0.00000000e+00]
 [ 2.99999993e-02  2.27177422e-02  0.00000000e+00]
 ...
 [ 2.24500008e+01 -1.51467025e-02 -1.00000005e-03]
 [ 2.24599991e+01 -5.68059133e-03 -1.00000005e-03]
 [ 2.24699993e+01 -1.51467025e-02 -1.00000005e-03]]


In [6]:
time = data[:,0]
force = data[:,1]
displacement = data[:,2]
print(displacement)

[ 0.     0.     0.    ... -0.001 -0.001 -0.001]
